name: zoomable_image
description: A plugin for panning and zooming images by touch.

author: perlatus <perlatus@zoomable_image.email.vczf.io>
homepage: https://github.com/perlatus/flutter_zoomable_image

version: 1.3.1+1
environment:
  sdk: ">=2.1.0 < 3.0.0"
publish_to: https://dartpub.boxview.com

dependencies:
  flutter:
    sdk: flutter
